# This file was automatically generated by SWIG (http://www.swig.org).
# Version 2.0.6
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.



from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_qrandom', [dirname(__file__)])
        except ImportError:
            import _qrandom
            return _qrandom
        if fp is not None:
            try:
                _mod = imp.load_module('_qrandom', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _qrandom = swig_import_helper()
    del swig_import_helper
else:
    import _qrandom
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0


class SizeError(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SizeError, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SizeError, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _qrandom.new_SizeError(*args)
        try: self.this.append(this)
        except: self.this = this
    def what(self): return _qrandom.SizeError_what(self)
    __swig_destroy__ = _qrandom.delete_SizeError
    __del__ = lambda self : None;
SizeError_swigregister = _qrandom.SizeError_swigregister
SizeError_swigregister(SizeError)

class GeneralizedHalton(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, GeneralizedHalton, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, GeneralizedHalton, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _qrandom.new_GeneralizedHalton(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _qrandom.delete_GeneralizedHalton
    __del__ = lambda self : None;
    def get(self, *args): return _qrandom.GeneralizedHalton_get(self, *args)
    def reset(self): return _qrandom.GeneralizedHalton_reset(self)
    def seed(self, inScrambling=None): return _qrandom.GeneralizedHalton_seed(self, inScrambling)
GeneralizedHalton_swigregister = _qrandom.GeneralizedHalton_swigregister
GeneralizedHalton_swigregister(GeneralizedHalton)

class Halton(GeneralizedHalton):
    __swig_setmethods__ = {}
    for _s in [GeneralizedHalton]: __swig_setmethods__.update(getattr(_s,'__swig_setmethods__',{}))
    __setattr__ = lambda self, name, value: _swig_setattr(self, Halton, name, value)
    __swig_getmethods__ = {}
    for _s in [GeneralizedHalton]: __swig_getmethods__.update(getattr(_s,'__swig_getmethods__',{}))
    __getattr__ = lambda self, name: _swig_getattr(self, Halton, name)
    __repr__ = _swig_repr
    def __init__(self, *args): 
        this = _qrandom.new_Halton(*args)
        try: self.this.append(this)
        except: self.this = this
    __swig_destroy__ = _qrandom.delete_Halton
    __del__ = lambda self : None;
Halton_swigregister = _qrandom.Halton_swigregister
Halton_swigregister(Halton)

# This file is compatible with both classic and new-style classes.


